robbit: CaptureScreen.h File Reference
Robbit v 4.0.0 Robbit Home
CaptureScreen.h File Reference
Functions
void CaptureScreen (char *filename)
Actual Capture screen routine.
Function Documentation
void CaptureScreen (char * filename)
Actual Capture screen routine.
Captures OpenGL render buffer. Creates a PNG file, writes header info, image data, and closes it.
Definition at line 26 of file CaptureScreen.h.
References PNGImage::initWriteStructs(), PNGImage::openFileWrite(), PNGImage::writeEnd(), PNGImage::writeHeader(), and PNGImage::writeImage().
Referenced by Frame_Display::CaptureScreenshot().