robbit: Robbit.cpp File Reference
Robbit v 4.0.0 Robbit Home
Robbit.cpp File Reference
#include "Definitions.h"
#include "DistancePointLine.h"
#include "WritePNG.h"
#include "CaptureScreen.h"
#include "Frame_Data.h"
#include "File_Data.h"
#include "File_Data.c"
#include "Frame_Display.h"
#include "Frame_Display.c"
#include "robbitGUI.h"
#include "robbitGUI.cxx"
#include "GetNextFrame.h"
Functions
void FileIdleProc (void *)
Idle function operating in log file mode.
void FunctionIdleProc (void *)
Idle function operating in custom algorithm mode.
void WriteInputFile ()
Writes log file in specified format.
int main (int argc, char **argv)
Main function.
Variables
RobbitUI robbit_gui
Function Documentation
void FileIdleProc (void *)
Idle function operating in log file mode.
When the simlation is run by reading data from pre-existing log file, this function handles the data handling and updating. It also sets the positions of the various light sources, numbered 0 through 3. It sets the floor size by reading through the data file once, and getting the maximum and minimum coordinates of the objects present in the arena. Sets the initial look-at coordinate. Updates the sleep time between frame renders. Also controls play/pause actions.
Definition at line 112 of file Robbit.cpp.
References Frame_Display::current_index, default_sleep_time, RobbitUI::display, File_Data::GetData(), RobbitUI::indexSlider, Frame_Display::is_paused, light0_pos, light1_pos, light2_pos, light3_pos, max_x, max_y, min_x, min_y, Frame_Display::render_speed, RobbitUI::RenderSpeedMenu, File_Data::SetFileInput(), Frame_Display::setStop(), Frame_Data::time_step, Frame_Display::UpdateFrame(), Frame_Display::view_centerX, Frame_Display::view_centerY, and Frame_Display::view_centerZ.
Referenced by main().
void FunctionIdleProc (void *)
Idle function operating in custom algorithm mode.
When the simlation is run by creating coordinate data using a custom algorithm, this function is used. Algorithm writers may use the above function, void FileIdleProc (void *) as reference while writing this function.
Definition at line 166 of file Robbit.cpp.
References RobbitUI::display, GetNextFrame(), Frame_Display::is_paused, light0_pos, light1_pos, light2_pos, light3_pos, max_x, max_y, min_x, min_y, Frame_Display::UpdateFrame(), Frame_Display::view_centerX, Frame_Display::view_centerY, and Frame_Display::view_centerZ.
Referenced by main().
int main (int argc, char ** argv)
Main function.
Displays splash screen, asks mode of operation (log file, custom algorithm, etc., starts simulation)
Parameters:
argc number of commandline arguments
argv array of commandline arguments
Returns:
0, except in case of error
Definition at line 56 of file Robbit.cpp.
References RobbitUI::display, FileIdleProc(), FunctionIdleProc(), RobbitUI::htmlSplash, Frame_Display::setDefaults(), RobbitUI::show(), RobbitUI::SplashWindow, start_time, update_frame_mode, and WriteInputFile().
void WriteInputFile ()
Writes log file in specified format.
Writes frame data including x & y coordinates, x & y velocities, orientation (), direction of velocity and other details for each object in the arena in a given format.
Any line starting with '' is treated as comment and is skipped while reading the log.
Each line contains the data for all the robots at a particular time. Following pseduo code expains the format.
fprintf(LogFile,"%4d %3.1f  ",iteration_number,tfly); // tfly: time between successive iterations
fprintf(LogFile,"%7.3f",current_time);
for i=0 to i<no_of_robots {
  fprintf(LogFile,"%7.2f %7.2f %6.3f %5.1f %5.1f ",x_pos_Robot[i],y_pos_Robot[i],orientation_Robot[i],Linear_Speed_Robot[i],Angular_velocity_Robots[i]);
}
fori=0 to i<NoofRobots {
  fprintf(LogFile,"%5.1f %5.1f ",x_velocity_Robots[i],y_velocity_Robots[i]);
}
fprintf(LogFile,"%5.1f %5.1f ",x_pos_ball,y_pos_ball);
fprintf(LogFile,"\n"); // end of current line
Definition at line 221 of file Robbit.cpp.
Referenced by main().
Variable Documentation
RobbitUI robbit_gui
Definition at line 43 of file Robbit.cpp.