robbit: File_Data Class Reference
Robbit v 4.0.0 Robbit Home
File_Data Class Reference
Class to store file data.
#include <File_Data.h>
Public Member Functions
int BuildFileIndex ()
Builds index for quick reference within log file.
int SetFileInput (const char *fname)
Opens the log file and calls BuildFileIndex().
int IndexSize () const
int GetData (int i, Frame_Data &data)
Get data from file index.
Protected Types
typedef std::size_t pos_type
Protected Attributes
std::vector< pos_type > file_index
std::ifstream input
Detailed Description
Class to store file data.
This record may be one from a log-file. It includes methods to build an index, to get based on the index, etc.
Definition at line 27 of file File_Data.h.
Member Typedef Documentation
typedef std::size_t File_Data::pos_type [protected]
Definition at line 30 of file File_Data.h.
Member Function Documentation
int File_Data::BuildFileIndex ()
Builds index for quick reference within log file.
Stores the positions of get pointers to valid records in the log file, in a vector. This way, the file does not need to be traversed in serial fashion, and allows for quicker and random access to file data.
Definition at line 47 of file file_data.c.
References file_index, input, max_x, max_y, min_x, min_y, and no_of_bots.
Referenced by SetFileInput().
int File_Data::SetFileInput (const char * fname)
Opens the log file and calls BuildFileIndex().
Parameters:
fname string : name of the log file to be opened
Definition at line 29 of file file_data.c.
References BuildFileIndex(), and input.
Referenced by FileIdleProc().
int File_Data::IndexSize () const [inline]
Definition at line 37 of file File_Data.h.
References file_index.
int File_Data::GetData (int ind, Frame_Data & data)
Get data from file index.
Reads each line pointed to by the get pointer locations stored in the index. Breaks each line into the required fields, and stores the fields into the object 'data' of class 'Frame_Data'.
Parameters:
ind current record number / index
data object 'data' of class 'Frame_Data'
Returns:
0 always
Definition at line 123 of file file_data.c.
References Frame_Data::ball_x, Frame_Data::ball_y, Frame_Data::bot_hit, Frame_Data::bot_orient, Frame_Data::bot_vorient, Frame_Data::bot_vx, Frame_Data::bot_vy, Frame_Data::bot_x, Frame_Data::bot_y, file_index, input, no_of_bots, Frame_Data::time, and Frame_Data::time_step.
Referenced by FileIdleProc().
Member Data Documentation
std::vector<pos_type> File_Data::file_index [protected]
Definition at line 31 of file File_Data.h.
Referenced by BuildFileIndex(), GetData(), and IndexSize().
std::ifstream File_Data::input [protected]
Definition at line 32 of file File_Data.h.
Referenced by BuildFileIndex(), GetData(), and SetFileInput().
The documentation for this class was generated from the following files:
File_Data.h
file_data.c