robbit: DistancePointLine.h File Reference
Robbit v 4.0.0 Robbit Home
DistancePointLine.h File Reference
Classes
struct tagXY
Contains x, y coordinates of a generic point.
Typedefs
typedef struct tagXY XY
Contains x, y coordinates of a generic point.
Functions
float Magnitude (XY *Point1, XY *Point2)
Distance between two points.
int DistancePointLine (XY *Point, XY *LineStart, XY *LineEnd, float radius_of_robot)
Evaluates if a bot lies on a line given by two points.
Typedef Documentation
typedef struct tagXY XY
Contains x, y coordinates of a generic point.
Function Documentation
int DistancePointLine (XY * Point, XY * LineStart, XY * LineEnd, float radius_of_robot)
Evaluates if a bot lies on a line given by two points.
Parameters:
Point XY point, center of robot
LineStart XY point, marks a point on the line
LineEnd XY point, marks a second point on the line
Returns:
0, if bot is not on the line; 1, if it is.
Definition at line 53 of file DistancePointLine.h.
References Magnitude(), tagXY::X, and tagXY::Y.
Referenced by Frame_Display::DetectObstacleCollision().
float Magnitude (XY * Point1, XY * Point2)
Distance between two points.
Parameters:
Point1 XY point
Point2 XY point
Returns:
Distance between two points as float
Definition at line 38 of file DistancePointLine.h.
References tagXY::X, and tagXY::Y.
Referenced by DistancePointLine().