robbit: RobbitUI Class Reference
Robbit v 4.0.0 Robbit Home
RobbitUI Class Reference
CLass to build the whole GUI.
#include <robbitGUI.h>
Public Member Functions
RobbitUI ()
void show ()
Public Attributes
Fl_Double_Window * RobbitMainWindow
Fl_Value_Slider * indexSlider
Frame_Display * display
Fl_Button * ButtonAbout
Fl_Light_Button * ToggleAutoView
Fl_Light_Button * ToggleTopView
Fl_Light_Button * ToggleTrails
Fl_Light_Button * ToggleObstacles
Fl_Light_Button * ToggleBotNumbering
Fl_Button * ButtonAdvSettings
Fl_Button * ButtonScrrenshot
Fl_Choice * RenderSpeedMenu
Fl_Choice * BotMenu
Fl_Choice * LightMenu
Fl_Button * ButtonReset
Fl_Button * ButtonPlayPause
Fl_Button * ButtonStop
Fl_Double_Window * AboutWindow
Fl_Help_View * textrobbit
Fl_Double_Window * SplashWindow
Fl_Help_View * htmlSplash
Fl_Double_Window * custom_robot_window
Fl_Input * height
Fl_Input * radius
Fl_Double_Window * AdvSettingsWindow
Fl_Input * maxy
Fl_Input * miny
Fl_Input * maxx
Fl_Input * minx
Fl_Input * ball_radius
Fl_Input * trail_points
Fl_Input * coloured_steps
Fl_Slider * graphics_quality
Static Public Attributes
static Fl_Menu_Item menu_RenderSpeedMenu []
static Fl_Menu_Item menu_BotMenu []
static Fl_Menu_Item * KheperaII = RobbitUI::menu_BotMenu + 0
static Fl_Menu_Item * KheperaIII = RobbitUI::menu_BotMenu + 1
static Fl_Menu_Item * Custom = RobbitUI::menu_BotMenu + 2
static Fl_Menu_Item menu_LightMenu []
static Fl_Menu_Item * Light1 = RobbitUI::menu_LightMenu + 0
static Fl_Menu_Item * Light2 = RobbitUI::menu_LightMenu + 1
static Fl_Menu_Item * Light3 = RobbitUI::menu_LightMenu + 2
static Fl_Menu_Item * Light4 = RobbitUI::menu_LightMenu + 3
Private Member Functions
void cb_RobbitMainWindow_i (Fl_Double_Window *, void *)
void cb_indexSlider_i (Fl_Value_Slider *, void *)
void cb_ButtonAbout_i (Fl_Button *, void *)
void cb_ToggleAutoView_i (Fl_Light_Button *, void *)
void cb_ToggleTopView_i (Fl_Light_Button *, void *)
void cb_ToggleTrails_i (Fl_Light_Button *, void *)
void cb_ToggleObstacles_i (Fl_Light_Button *, void *)
void cb_ToggleBotNumbering_i (Fl_Light_Button *, void *)
void cb_ButtonAdvSettings_i (Fl_Button *, void *)
void cb_ButtonScrrenshot_i (Fl_Button *, void *)
void cb_0_i (Fl_Menu_ *, void *)
void cb_1X_i (Fl_Menu_ *, void *)
void cb_2X_i (Fl_Menu_ *, void *)
void cb_5X_i (Fl_Menu_ *, void *)
void cb_10X_i (Fl_Menu_ *, void *)
void cb_MAX_i (Fl_Menu_ *, void *)
void cb_KheperaII_i (Fl_Menu_ *, void *)
void cb_KheperaIII_i (Fl_Menu_ *, void *)
void cb_Custom_i (Fl_Menu_ *, void *)
void cb_Light1_i (Fl_Menu_ *, void *)
void cb_Light2_i (Fl_Menu_ *, void *)
void cb_Light3_i (Fl_Menu_ *, void *)
void cb_Light4_i (Fl_Menu_ *, void *)
void cb_ButtonReset_i (Fl_Button *, void *)
void cb_ButtonPlayPause_i (Fl_Button *, void *)
void cb_ButtonStop_i (Fl_Button *, void *)
void cb_About_i (Fl_Button *, void *)
void cb_Close_i (Fl_Return_Button *, void *)
void cb_OK_i (Fl_Return_Button *, void *)
void cb_maxy_i (Fl_Input *, void *)
void cb_miny_i (Fl_Input *, void *)
void cb_maxx_i (Fl_Input *, void *)
void cb_minx_i (Fl_Input *, void *)
void cb_ball_radius_i (Fl_Input *, void *)
void cb_trail_points_i (Fl_Input *, void *)
void cb_coloured_steps_i (Fl_Input *, void *)
void cb_graphics_quality_i (Fl_Slider *, void *)
void cb_OK1_i (Fl_Return_Button *, void *)
Static Private Member Functions
static void cb_RobbitMainWindow (Fl_Double_Window *, void *)
static void cb_indexSlider (Fl_Value_Slider *, void *)
static void cb_ButtonAbout (Fl_Button *, void *)
static void cb_ToggleAutoView (Fl_Light_Button *, void *)
static void cb_ToggleTopView (Fl_Light_Button *, void *)
static void cb_ToggleTrails (Fl_Light_Button *, void *)
static void cb_ToggleObstacles (Fl_Light_Button *, void *)
static void cb_ToggleBotNumbering (Fl_Light_Button *, void *)
static void cb_ButtonAdvSettings (Fl_Button *, void *)
static void cb_ButtonScrrenshot (Fl_Button *, void *)
static void cb_0 (Fl_Menu_ *, void *)
static void cb_1X (Fl_Menu_ *, void *)
static void cb_2X (Fl_Menu_ *, void *)
static void cb_5X (Fl_Menu_ *, void *)
static void cb_10X (Fl_Menu_ *, void *)
static void cb_MAX (Fl_Menu_ *, void *)
static void cb_KheperaII (Fl_Menu_ *, void *)
static void cb_KheperaIII (Fl_Menu_ *, void *)
static void cb_Custom (Fl_Menu_ *, void *)
static void cb_Light1 (Fl_Menu_ *, void *)
static void cb_Light2 (Fl_Menu_ *, void *)
static void cb_Light3 (Fl_Menu_ *, void *)
static void cb_Light4 (Fl_Menu_ *, void *)
static void cb_ButtonReset (Fl_Button *, void *)
static void cb_ButtonPlayPause (Fl_Button *, void *)
static void cb_ButtonStop (Fl_Button *, void *)
static void cb_About (Fl_Button *, void *)
static void cb_Close (Fl_Return_Button *, void *)
static void cb_OK (Fl_Return_Button *, void *)
static void cb_maxy (Fl_Input *, void *)
static void cb_miny (Fl_Input *, void *)
static void cb_maxx (Fl_Input *, void *)
static void cb_minx (Fl_Input *, void *)
static void cb_ball_radius (Fl_Input *, void *)
static void cb_trail_points (Fl_Input *, void *)
static void cb_coloured_steps (Fl_Input *, void *)
static void cb_graphics_quality (Fl_Slider *, void *)
static void cb_OK1 (Fl_Return_Button *, void *)
Detailed Description
CLass to build the whole GUI.
This class is created with FLUID (Fast Light User-Interface Designer). It also monitors all the events and callback
Definition at line 45 of file robbitGUI.h.
Constructor & Destructor Documentation
RobbitUI::RobbitUI ()
Definition at line 321 of file robbitGUI.cxx.
References AboutWindow, AdvSettingsWindow, ball_radius, BotMenu, ButtonAbout, ButtonAdvSettings, ButtonPlayPause, ButtonReset, ButtonScrrenshot, ButtonStop, cb_About(), cb_ball_radius(), cb_ButtonAbout(), cb_ButtonAdvSettings(), cb_ButtonPlayPause(), cb_ButtonReset(), cb_ButtonScrrenshot(), cb_ButtonStop(), cb_Close(), cb_coloured_steps(), cb_graphics_quality(), cb_indexSlider(), cb_maxx(), cb_maxy(), cb_minx(), cb_miny(), cb_OK(), cb_OK1(), cb_RobbitMainWindow(), cb_ToggleAutoView(), cb_ToggleBotNumbering(), cb_ToggleObstacles(), cb_ToggleTopView(), cb_ToggleTrails(), cb_trail_points(), coloured_steps, custom_robot_window, display, graphics_quality, height, htmlSplash, indexSlider, LightMenu, maxx, maxy, menu_BotMenu, menu_LightMenu, menu_RenderSpeedMenu, minx, miny, radius, RenderSpeedMenu, RobbitMainWindow, SplashWindow, textrobbit, ToggleAutoView, ToggleBotNumbering, ToggleObstacles, ToggleTopView, ToggleTrails, and trail_points.
Member Function Documentation
void RobbitUI::cb_RobbitMainWindow_i (Fl_Double_Window * , void *) [private]
Definition at line 5 of file robbitGUI.cxx.
References display, and Frame_Display::setExit().
void RobbitUI::cb_RobbitMainWindow (Fl_Double_Window * o, void * v) [static, private]
Definition at line 8 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_indexSlider_i (Fl_Value_Slider * o, void *) [private]
Definition at line 12 of file robbitGUI.cxx.
References display, and Frame_Display::setIndex().
void RobbitUI::cb_indexSlider (Fl_Value_Slider * o, void * v) [static, private]
Definition at line 15 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_ButtonAbout_i (Fl_Button * , void *) [private]
Definition at line 19 of file robbitGUI.cxx.
References AboutWindow, and textrobbit.
void RobbitUI::cb_ButtonAbout (Fl_Button * o, void * v) [static, private]
Definition at line 23 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_ToggleAutoView_i (Fl_Light_Button * o, void *) [private]
Definition at line 27 of file robbitGUI.cxx.
References display, Frame_Display::setAutoView(), and ToggleTopView.
void RobbitUI::cb_ToggleAutoView (Fl_Light_Button * o, void * v) [static, private]
Definition at line 34 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_ToggleTopView_i (Fl_Light_Button * o, void *) [private]
Definition at line 38 of file robbitGUI.cxx.
References display, Frame_Display::setTopView(), and ToggleAutoView.
void RobbitUI::cb_ToggleTopView (Fl_Light_Button * o, void * v) [static, private]
Definition at line 45 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_ToggleTrails_i (Fl_Light_Button * o, void *) [private]
Definition at line 49 of file robbitGUI.cxx.
References display, and Frame_Display::setTrails().
void RobbitUI::cb_ToggleTrails (Fl_Light_Button * o, void * v) [static, private]
Definition at line 52 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_ToggleObstacles_i (Fl_Light_Button * o, void *) [private]
Definition at line 56 of file robbitGUI.cxx.
References display, and Frame_Display::setObstacles().
void RobbitUI::cb_ToggleObstacles (Fl_Light_Button * o, void * v) [static, private]
Definition at line 59 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_ToggleBotNumbering_i (Fl_Light_Button * o, void *) [private]
Definition at line 63 of file robbitGUI.cxx.
References display, and Frame_Display::setBotNumbering().
void RobbitUI::cb_ToggleBotNumbering (Fl_Light_Button * o, void * v) [static, private]
Definition at line 66 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_ButtonAdvSettings_i (Fl_Button * , void *) [private]
Definition at line 70 of file robbitGUI.cxx.
References AdvSettingsWindow, display, and Frame_Display::initAdvWindow().
void RobbitUI::cb_ButtonAdvSettings (Fl_Button * o, void * v) [static, private]
Definition at line 74 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_ButtonScrrenshot_i (Fl_Button * , void *) [private]
Definition at line 78 of file robbitGUI.cxx.
References Frame_Display::CaptureScreenshot(), and display.
void RobbitUI::cb_ButtonScrrenshot (Fl_Button * o, void * v) [static, private]
Definition at line 81 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_0_i (Fl_Menu_ * , void *) [private]
Definition at line 85 of file robbitGUI.cxx.
References display, and Frame_Display::setRenderSpeed().
void RobbitUI::cb_0 (Fl_Menu_ * o, void * v) [static, private]
Definition at line 88 of file robbitGUI.cxx.
void RobbitUI::cb_1X_i (Fl_Menu_ * , void *) [private]
Definition at line 92 of file robbitGUI.cxx.
References display, and Frame_Display::setRenderSpeed().
void RobbitUI::cb_1X (Fl_Menu_ * o, void * v) [static, private]
Definition at line 95 of file robbitGUI.cxx.
void RobbitUI::cb_2X_i (Fl_Menu_ * , void *) [private]
Definition at line 99 of file robbitGUI.cxx.
References display, and Frame_Display::setRenderSpeed().
void RobbitUI::cb_2X (Fl_Menu_ * o, void * v) [static, private]
Definition at line 102 of file robbitGUI.cxx.
void RobbitUI::cb_5X_i (Fl_Menu_ * , void *) [private]
Definition at line 106 of file robbitGUI.cxx.
References display, and Frame_Display::setRenderSpeed().
void RobbitUI::cb_5X (Fl_Menu_ * o, void * v) [static, private]
Definition at line 109 of file robbitGUI.cxx.
void RobbitUI::cb_10X_i (Fl_Menu_ * , void *) [private]
Definition at line 113 of file robbitGUI.cxx.
References display, and Frame_Display::setRenderSpeed().
void RobbitUI::cb_10X (Fl_Menu_ * o, void * v) [static, private]
Definition at line 116 of file robbitGUI.cxx.
void RobbitUI::cb_MAX_i (Fl_Menu_ * , void *) [private]
Definition at line 120 of file robbitGUI.cxx.
References display, and Frame_Display::setRenderSpeed().
void RobbitUI::cb_MAX (Fl_Menu_ * o, void * v) [static, private]
Definition at line 123 of file robbitGUI.cxx.
void RobbitUI::cb_KheperaII_i (Fl_Menu_ * , void *) [private]
Definition at line 137 of file robbitGUI.cxx.
References display, and Frame_Display::selectBot().
void RobbitUI::cb_KheperaII (Fl_Menu_ * o, void * v) [static, private]
Definition at line 140 of file robbitGUI.cxx.
void RobbitUI::cb_KheperaIII_i (Fl_Menu_ * , void *) [private]
Definition at line 144 of file robbitGUI.cxx.
References display, and Frame_Display::selectBot().
void RobbitUI::cb_KheperaIII (Fl_Menu_ * o, void * v) [static, private]
Definition at line 147 of file robbitGUI.cxx.
void RobbitUI::cb_Custom_i (Fl_Menu_ * , void *) [private]
Definition at line 151 of file robbitGUI.cxx.
References custom_robot_window.
void RobbitUI::cb_Custom (Fl_Menu_ * o, void * v) [static, private]
Definition at line 154 of file robbitGUI.cxx.
void RobbitUI::cb_Light1_i (Fl_Menu_ * , void *) [private]
Definition at line 168 of file robbitGUI.cxx.
References display, and Frame_Display::setLights().
void RobbitUI::cb_Light1 (Fl_Menu_ * o, void * v) [static, private]
Definition at line 171 of file robbitGUI.cxx.
void RobbitUI::cb_Light2_i (Fl_Menu_ * , void *) [private]
Definition at line 175 of file robbitGUI.cxx.
References display, and Frame_Display::setLights().
void RobbitUI::cb_Light2 (Fl_Menu_ * o, void * v) [static, private]
Definition at line 178 of file robbitGUI.cxx.
void RobbitUI::cb_Light3_i (Fl_Menu_ * , void *) [private]
Definition at line 182 of file robbitGUI.cxx.
References display, and Frame_Display::setLights().
void RobbitUI::cb_Light3 (Fl_Menu_ * o, void * v) [static, private]
Definition at line 185 of file robbitGUI.cxx.
void RobbitUI::cb_Light4_i (Fl_Menu_ * , void *) [private]
Definition at line 189 of file robbitGUI.cxx.
References display, and Frame_Display::setLights().
void RobbitUI::cb_Light4 (Fl_Menu_ * o, void * v) [static, private]
Definition at line 192 of file robbitGUI.cxx.
void RobbitUI::cb_ButtonReset_i (Fl_Button * , void *) [private]
Definition at line 208 of file robbitGUI.cxx.
References display, and Frame_Display::setReset().
void RobbitUI::cb_ButtonReset (Fl_Button * o, void * v) [static, private]
Definition at line 211 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_ButtonPlayPause_i (Fl_Button * , void *) [private]
Definition at line 215 of file robbitGUI.cxx.
References display, and Frame_Display::setPlayPause().
void RobbitUI::cb_ButtonPlayPause (Fl_Button * o, void * v) [static, private]
Definition at line 218 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_ButtonStop_i (Fl_Button * , void *) [private]
Definition at line 222 of file robbitGUI.cxx.
References display, and Frame_Display::setStop().
void RobbitUI::cb_ButtonStop (Fl_Button * o, void * v) [static, private]
Definition at line 225 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_About_i (Fl_Button * , void *) [private]
Definition at line 229 of file robbitGUI.cxx.
References AboutWindow, SplashWindow, start_time, and textrobbit.
void RobbitUI::cb_About (Fl_Button * o, void * v) [static, private]
Definition at line 236 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_Close_i (Fl_Return_Button * , void *) [private]
Definition at line 240 of file robbitGUI.cxx.
References SplashWindow, and start_time.
void RobbitUI::cb_Close (Fl_Return_Button * o, void * v) [static, private]
Definition at line 245 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_OK_i (Fl_Return_Button * , void *) [private]
Definition at line 249 of file robbitGUI.cxx.
References custom_robot_window, display, height, radius, and Frame_Display::setCustomRobot().
void RobbitUI::cb_OK (Fl_Return_Button * o, void * v) [static, private]
Definition at line 254 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_maxy_i (Fl_Input * , void *) [private]
Definition at line 258 of file robbitGUI.cxx.
References display, maxx, maxy, minx, miny, and Frame_Display::setArena().
void RobbitUI::cb_maxy (Fl_Input * o, void * v) [static, private]
Definition at line 261 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_miny_i (Fl_Input * , void *) [private]
Definition at line 265 of file robbitGUI.cxx.
References display, maxx, maxy, minx, miny, and Frame_Display::setArena().
void RobbitUI::cb_miny (Fl_Input * o, void * v) [static, private]
Definition at line 268 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_maxx_i (Fl_Input * , void *) [private]
Definition at line 272 of file robbitGUI.cxx.
References display, maxx, maxy, minx, miny, and Frame_Display::setArena().
void RobbitUI::cb_maxx (Fl_Input * o, void * v) [static, private]
Definition at line 275 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_minx_i (Fl_Input * , void *) [private]
Definition at line 279 of file robbitGUI.cxx.
References display, maxx, maxy, minx, miny, and Frame_Display::setArena().
void RobbitUI::cb_minx (Fl_Input * o, void * v) [static, private]
Definition at line 282 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_ball_radius_i (Fl_Input * o, void *) [private]
Definition at line 286 of file robbitGUI.cxx.
References display, and Frame_Display::setBallRadius().
void RobbitUI::cb_ball_radius (Fl_Input * o, void * v) [static, private]
Definition at line 289 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_trail_points_i (Fl_Input * o, void *) [private]
Definition at line 293 of file robbitGUI.cxx.
References display, and Frame_Display::setTrailPoints().
void RobbitUI::cb_trail_points (Fl_Input * o, void * v) [static, private]
Definition at line 296 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_coloured_steps_i (Fl_Input * o, void *) [private]
Definition at line 300 of file robbitGUI.cxx.
References display, and Frame_Display::setColouredSteps().
void RobbitUI::cb_coloured_steps (Fl_Input * o, void * v) [static, private]
Definition at line 303 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_graphics_quality_i (Fl_Slider * o, void *) [private]
Definition at line 307 of file robbitGUI.cxx.
References display, and Frame_Display::setGraphicsQuality().
void RobbitUI::cb_graphics_quality (Fl_Slider * o, void * v) [static, private]
Definition at line 310 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::cb_OK1_i (Fl_Return_Button * , void *) [private]
Definition at line 314 of file robbitGUI.cxx.
References AdvSettingsWindow.
void RobbitUI::cb_OK1 (Fl_Return_Button * o, void * v) [static, private]
Definition at line 317 of file robbitGUI.cxx.
Referenced by RobbitUI().
void RobbitUI::show ()
Definition at line 575 of file robbitGUI.cxx.
References RobbitMainWindow.
Referenced by main().
Member Data Documentation
Fl_Double_Window* RobbitUI::RobbitMainWindow
Definition at line 48 of file robbitGUI.h.
Referenced by RobbitUI(), and show().
Fl_Value_Slider* RobbitUI::indexSlider
Definition at line 53 of file robbitGUI.h.
Referenced by FileIdleProc(), RobbitUI(), and Frame_Display::setStop().
Frame_Display* RobbitUI::display
Definition at line 58 of file robbitGUI.h.
Referenced by cb_0_i(), cb_10X_i(), cb_1X_i(), cb_2X_i(), cb_5X_i(), cb_ball_radius_i(), cb_ButtonAdvSettings_i(), cb_ButtonPlayPause_i(), cb_ButtonReset_i(), cb_ButtonScrrenshot_i(), cb_ButtonStop_i(), cb_coloured_steps_i(), cb_graphics_quality_i(), cb_indexSlider_i(), cb_KheperaII_i(), cb_KheperaIII_i(), cb_Light1_i(), cb_Light2_i(), cb_Light3_i(), cb_Light4_i(), cb_MAX_i(), cb_maxx_i(), cb_maxy_i(), cb_minx_i(), cb_miny_i(), cb_OK_i(), cb_RobbitMainWindow_i(), cb_ToggleAutoView_i(), cb_ToggleBotNumbering_i(), cb_ToggleObstacles_i(), cb_ToggleTopView_i(), cb_ToggleTrails_i(), cb_trail_points_i(), FileIdleProc(), FunctionIdleProc(), main(), and RobbitUI().
Fl_Button* RobbitUI::ButtonAbout
Definition at line 59 of file robbitGUI.h.
Referenced by RobbitUI().
Fl_Light_Button* RobbitUI::ToggleAutoView
Definition at line 64 of file robbitGUI.h.
Referenced by cb_ToggleTopView_i(), Frame_Display::handle(), and RobbitUI().
Fl_Light_Button* RobbitUI::ToggleTopView
Definition at line 69 of file robbitGUI.h.
Referenced by cb_ToggleAutoView_i(), Frame_Display::handle(), RobbitUI(), and Frame_Display::setDefaults().
Fl_Light_Button* RobbitUI::ToggleTrails
Definition at line 74 of file robbitGUI.h.
Referenced by Frame_Display::handle(), RobbitUI(), and Frame_Display::setDefaults().
Fl_Light_Button* RobbitUI::ToggleObstacles
Definition at line 79 of file robbitGUI.h.
Referenced by Frame_Display::handle(), RobbitUI(), and Frame_Display::setDefaults().
Fl_Light_Button* RobbitUI::ToggleBotNumbering
Definition at line 84 of file robbitGUI.h.
Referenced by Frame_Display::handle(), RobbitUI(), and Frame_Display::setDefaults().
Fl_Button* RobbitUI::ButtonAdvSettings
Definition at line 89 of file robbitGUI.h.
Referenced by RobbitUI().
Fl_Button* RobbitUI::ButtonScrrenshot
Definition at line 94 of file robbitGUI.h.
Referenced by RobbitUI().
Fl_Choice* RobbitUI::RenderSpeedMenu
Definition at line 99 of file robbitGUI.h.
Referenced by FileIdleProc(), RobbitUI(), and Frame_Display::setDefaults().
Fl_Menu_Item RobbitUI::menu_RenderSpeedMenu [static]
Initial value:
 {
 {"0.5X", 0,  (Fl_Callback*)RobbitUI::cb_0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"1X", 0,  (Fl_Callback*)RobbitUI::cb_1X, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"2X", 0,  (Fl_Callback*)RobbitUI::cb_2X, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"5X", 0,  (Fl_Callback*)RobbitUI::cb_5X, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"10X", 0,  (Fl_Callback*)RobbitUI::cb_10X, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"MAX", 0,  (Fl_Callback*)RobbitUI::cb_MAX, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 100 of file robbitGUI.h.
Referenced by RobbitUI().
Fl_Choice* RobbitUI::BotMenu
Definition at line 115 of file robbitGUI.h.
Referenced by RobbitUI(), and Frame_Display::setDefaults().
Fl_Menu_Item RobbitUI::menu_BotMenu [static]
Initial value:
 {
 {"Khepera II", 0,  (Fl_Callback*)RobbitUI::cb_KheperaII, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Khepera III", 0,  (Fl_Callback*)RobbitUI::cb_KheperaIII, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Custom", 0,  (Fl_Callback*)RobbitUI::cb_Custom, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 116 of file robbitGUI.h.
Referenced by RobbitUI().
Fl_Menu_Item * RobbitUI::KheperaII = RobbitUI::menu_BotMenu + 0 [static]
Definition at line 117 of file robbitGUI.h.
Fl_Menu_Item * RobbitUI::KheperaIII = RobbitUI::menu_BotMenu + 1 [static]
Definition at line 122 of file robbitGUI.h.
Fl_Menu_Item * RobbitUI::Custom = RobbitUI::menu_BotMenu + 2 [static]
Definition at line 127 of file robbitGUI.h.
Fl_Choice* RobbitUI::LightMenu
Definition at line 132 of file robbitGUI.h.
Referenced by RobbitUI(), and Frame_Display::setDefaults().
Fl_Menu_Item RobbitUI::menu_LightMenu [static]
Initial value:
 {
 {"1", 0,  (Fl_Callback*)RobbitUI::cb_Light1, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"2", 0,  (Fl_Callback*)RobbitUI::cb_Light2, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"3", 0,  (Fl_Callback*)RobbitUI::cb_Light3, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"4", 0,  (Fl_Callback*)RobbitUI::cb_Light4, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
}
Definition at line 133 of file robbitGUI.h.
Referenced by RobbitUI().
Fl_Menu_Item * RobbitUI::Light1 = RobbitUI::menu_LightMenu + 0 [static]
Definition at line 134 of file robbitGUI.h.
Fl_Menu_Item * RobbitUI::Light2 = RobbitUI::menu_LightMenu + 1 [static]
Definition at line 139 of file robbitGUI.h.
Fl_Menu_Item * RobbitUI::Light3 = RobbitUI::menu_LightMenu + 2 [static]
Definition at line 144 of file robbitGUI.h.
Fl_Menu_Item * RobbitUI::Light4 = RobbitUI::menu_LightMenu + 3 [static]
Definition at line 149 of file robbitGUI.h.
Fl_Button* RobbitUI::ButtonReset
Definition at line 154 of file robbitGUI.h.
Referenced by RobbitUI().
Fl_Button* RobbitUI::ButtonPlayPause
Definition at line 159 of file robbitGUI.h.
Referenced by RobbitUI(), Frame_Display::setDefaults(), Frame_Display::setPlayPause(), and Frame_Display::setStop().
Fl_Button* RobbitUI::ButtonStop
Definition at line 164 of file robbitGUI.h.
Referenced by RobbitUI().
Fl_Double_Window* RobbitUI::AboutWindow
Definition at line 169 of file robbitGUI.h.
Referenced by cb_About_i(), cb_ButtonAbout_i(), Frame_Display::handle(), and RobbitUI().
Fl_Help_View* RobbitUI::textrobbit
Definition at line 170 of file robbitGUI.h.
Referenced by cb_About_i(), cb_ButtonAbout_i(), Frame_Display::handle(), and RobbitUI().
Fl_Double_Window* RobbitUI::SplashWindow
Definition at line 171 of file robbitGUI.h.
Referenced by cb_About_i(), cb_Close_i(), main(), and RobbitUI().
Fl_Help_View* RobbitUI::htmlSplash
Definition at line 172 of file robbitGUI.h.
Referenced by main(), and RobbitUI().
Fl_Double_Window* RobbitUI::custom_robot_window
Definition at line 179 of file robbitGUI.h.
Referenced by cb_Custom_i(), cb_OK_i(), and RobbitUI().
Fl_Input* RobbitUI::height
Definition at line 180 of file robbitGUI.h.
Referenced by cb_OK_i(), and RobbitUI().
Fl_Input* RobbitUI::radius
Definition at line 181 of file robbitGUI.h.
Referenced by cb_OK_i(), and RobbitUI().
Fl_Double_Window* RobbitUI::AdvSettingsWindow
Definition at line 186 of file robbitGUI.h.
Referenced by cb_ButtonAdvSettings_i(), cb_OK1_i(), Frame_Display::handle(), and RobbitUI().
Fl_Input* RobbitUI::maxy
Definition at line 187 of file robbitGUI.h.
Referenced by cb_maxx_i(), cb_maxy_i(), cb_minx_i(), cb_miny_i(), Frame_Display::initAdvWindow(), and RobbitUI().
Fl_Input* RobbitUI::miny
Definition at line 192 of file robbitGUI.h.
Referenced by cb_maxx_i(), cb_maxy_i(), cb_minx_i(), cb_miny_i(), Frame_Display::initAdvWindow(), and RobbitUI().
Fl_Input* RobbitUI::maxx
Definition at line 197 of file robbitGUI.h.
Referenced by cb_maxx_i(), cb_maxy_i(), cb_minx_i(), cb_miny_i(), Frame_Display::initAdvWindow(), and RobbitUI().
Fl_Input* RobbitUI::minx
Definition at line 202 of file robbitGUI.h.
Referenced by cb_maxx_i(), cb_maxy_i(), cb_minx_i(), cb_miny_i(), Frame_Display::initAdvWindow(), and RobbitUI().
Fl_Input* RobbitUI::ball_radius
Definition at line 207 of file robbitGUI.h.
Referenced by Frame_Display::initAdvWindow(), and RobbitUI().
Fl_Input* RobbitUI::trail_points
Definition at line 212 of file robbitGUI.h.
Referenced by Frame_Display::initAdvWindow(), and RobbitUI().
Fl_Input* RobbitUI::coloured_steps
Definition at line 217 of file robbitGUI.h.
Referenced by Frame_Display::initAdvWindow(), and RobbitUI().
Fl_Slider* RobbitUI::graphics_quality
Definition at line 222 of file robbitGUI.h.
Referenced by Frame_Display::initAdvWindow(), and RobbitUI().
The documentation for this class was generated from the following files:
robbitGUI.h
robbitGUI.cxx